0xFacet/facet-vm

app/controllers/status_controller.rb
app/models/contract.rb
app/models/contract_call_receipt.rb
app/models/contract_implementation.rb
app/models/contract_proxy.rb
app/models/contract_transaction.rb
app/models/contracts/erc20.rb
app/models/contracts/erc20_liquidity_pool.rb
app/models/contracts/erc721.rb
app/models/contracts/ether_erc20_bridge.rb
app/models/contracts/ethscription_erc20_bridge.rb
app/models/contracts/generative_erc721.rb
app/models/contracts/open_edition_erc721.rb
app/models/contracts/public_mint_erc20.rb
app/models/ethscription_sync.rb
app/models/state_proxy.rb

To this point, contracts have been defined as subclasses of the `Contract` ActiveRecord class. Defining contracts and managing their persistence are different contexts and the shared namespace leads to conflicts.
For example, if we want to have an `address` function within contracts that allows us to write `emit :Transfer, from: address(0), to: to, amount: amount`, we cannot also have an `address` column on our contracts table because ActiveRecord automatically defines methods based on column names and we cannot have two methods called `address`.
This pull request fixes the situation by creating a new `ContractImplementation` class whose methods pertain (almost) exclusively to defining contracts.

Refactor contract definition context with `ContractImplementation`

---

app/controllers/contracts_controller.rb
app/models/contract_call_receipt.rb
app/models/contract_state.rb
app/models/contract_test_helper.rb
app/models/contract_transaction.rb
config/routes.rb
spec/contracts_controller_spec.rb
spec/models/contract_spec.rb

Create an API endpoint that allows users to simulate transactions. The response of this endpoint will be the call receipt that would have been generated had the transaction not been a simulation.
The simulations are available at `/contracts/simulate/:command`, where `command` is either `deploy` or `call`.
Required URL params:
- from: the `msg.sender` of the simulated transaction.
- data: the data payload, i.e., the JSON part of the ethscription, including contract id, function name, and args. This should be JSON-encoded, just as it would be in the body of an ethscription.
For example, if
- from =`0xC2172a6315c1D7f6855768F843c420EbB36eDa97`
- data = `{"protocol":"PublicMintERC20","constructorArgs":{"name":"My+Fun+Token","symbol":"FUN","maxSupply":"21000000","perMintLimit":"1000","decimals": …

Transaction Simulation

---

app/models/abi_proxy.rb
app/models/contract.rb
app/models/contract_proxy.rb
app/models/contract_transaction.rb
app/models/contracts/erc20_liquidity_pool.rb
app/models/contracts/erc721.rb
app/models/function_context.rb
spec/models/contract_spec.rb
spec/models/rubidity_spec.rb

Previously you had to write `_mint(to: msg.sender, amount: amount)`. Now you can write `_mint(msg.sender, amount)`.
The old system was particularly annoying in the case of auto-generated getter functions which were automatically assigned argument names `arg0`, `arg1` etc.

Enable the use of non-keyword function args

---

app/models/type.rb

`Integer(str)` has some weird behavior when you don't specify the base, so let's be explicit.

Integers explicitly support base 10 and base 16

---

app/models/contract_transaction.rb
app/models/contract_transaction_globals.rb
app/models/ethscription.rb

When we simulate a transaction we use a fake Ethscription as the input data. In almost all cases this is fine because the VM is a closed system that doesn't depend on external reality.
However, when performing `findEthscriptionById` we need to look up an ethscription in the base protocol indexer and we need to ensure that the state of this looked up ethscription is synced with the state of the ethscription making the VM transaction.
This means the base protocol indexer must know about the ethscription making the transaction, and this is obviously not possible if this ethscription is fake.
To fix this and enable us to simulate transactions that involve `findEthscriptionById`, in the case of a simulation we tell the base protocol indexer to return results valid as of the most recent …

Fix bug relating to simulating findEthscriptionById

---

app/models/abi_proxy.rb
app/models/contract_errors.rb
app/models/contract_implementation.rb
app/models/contract_test_helper.rb
app/models/contract_transaction.rb
spec/models/inheritance_spec.rb

Rubidity can't use Ruby's built in `super` functionality because of the way we define functions and also because Ruby doesn't support multiple inheritance. So Rubidity must implement inheritance from scratch.
The initial implementation attempted to create a "poor man's" `super` from scratch using `_super_{method_name}` but all it did was grab the closest parent's implementation and run it in the context of the child.
This breaks with an infinite loop in the case the parent also calls `_super_{method_name}` because the parent's function is evaluated in the context of the child and so the parent's call to `_super_{method_name}` is the same the child calling it again, causing a loop.
To fix this, we remove the notion of `super`. Instead, you must specify the parent you are calling with …

Refactor inheritance to remove 'super' concept

---

app/models/abi_proxy.rb
app/models/array_type.rb
app/models/contract_errors.rb
app/models/contract_implementation.rb
app/models/contract_test_helper.rb
app/models/contract_transaction_globals.rb
app/models/contracts/erc20.rb
app/models/contracts/public_mint_erc20.rb
app/models/mapping_type.rb
app/models/state_proxy.rb
app/models/state_variable.rb
app/models/type.rb
app/models/typed_variable.rb
spec/models/inheritance_spec.rb
spec/models/type_spec.rb
spec/models/typed_variable_spec.rb

My original goal was to add the missing `int`s and `uint`s below the `uint256` / `int256` types we already have.
There is some subtlety to these types, however. All `uint` / `int` values can be compared, but values from larger types cannot be assigned to variables of smaller types.
I.e., you can compare `uint256` and `uint8`, you can assign `uint8` to `uint256`, but you can't assign `uint256` to `uint8`.
To capture this logic I formalized the `can_be_assigned_from?` and `values_can_be_compared?` relationships in the `Type` model.
I refactored `TypedVariable.create` into `create` and `create_or_validate` so we are forced to know whether we're dealing with a literal or an existing `TypedVariable`
Finally I updated the `==` on `TypedVariable` to raise an exception when the types aren't …

Add more ints, refactor type system

---

app/models/abi_proxy.rb
app/models/contracts/ether_erc20_bridge.rb
app/models/contracts/ethscription_erc20_bridge.rb
app/models/contracts/generative_erc721.rb
app/models/contracts/open_edition_erc721.rb
app/models/contracts/public_mint_erc20.rb

`ERC(args)` is better used for deploying contracts than as syntactic sugar for calling parent constructors. Someday we'll get rid of the leading _.

Use more annoying syntax for calling parent constructors

---

app/models/contract.rb
app/models/contract_implementation.rb
app/models/contract_transaction.rb
spec/models/inheritance_spec.rb

The initial contract implementation used Rails's Single Table Inheritance pattern which requires you to put the full class name in the `type` column.
We ditched STI a while ago and yet are still storing types like `Contracts::PublicMintERC20`. Now that we're invalidating all the old data anyway it's a good time to eliminate the annoying prefix!

Eliminate the `Contracts::` prefix on contract types

---

app/models/contract.rb
app/models/contract_implementation.rb
app/models/contract_transaction.rb
app/models/contracts/erc20_liquidity_pool.rb
spec/models/contract_implementation_spec.rb

Now you can say `ERC20(s.token0).balanceOf(address(this))` and it will verify if the contract you're trying to call implements `ERC20`.

Better contract type casting

---

app/models/contract.rb
app/models/contract_implementation.rb
config/environments/test.rb

This is a more direct way of defining them and it doesn't rely on `method_missing` which should be a last resort.
Also enabled eager loading in test which is annoying because it makes things slower but we have no choice!

Refactor valid contract type computation

---

app/models/abi_proxy.rb
app/models/contract_implementation.rb
app/models/contract_proxy.rb
app/models/contracts/ether_erc20_bridge.rb
app/models/contracts/ethscription_erc20_bridge.rb
app/models/contracts/generative_erc721.rb
app/models/contracts/open_edition_erc721.rb
app/models/contracts/public_mint_erc20.rb
app/models/function_context.rb
app/models/transaction_context.rb
spec/models/contract_implementation_spec.rb
spec/models/inheritance_spec.rb

Now that we have `TransactionContext` managing our global transaction state we can finally have "the good version" and use `ERC20._mint()` instead of `_ERC20._mint()`.
This is because the "good version" relies on knowing the "current contract" which was not really possible under our previous approach to state.

Improve syntax for calling parent contracts

---

app/models/contract_implementation.rb
app/models/transaction_context.rb

This way you can call `this.balanceOf()` etc. It's also how it was before.

`this` should be a `ContractImplementation`, not a `Contract` record

---

app/models/abi_proxy.rb
app/models/contract_errors.rb
app/models/contracts/erc20_liquidity_pool.rb
spec/models/contract_spec.rb

Like so:
```solidity
function :reserves, {}, :public, :view, returns: { token0: :uint256, token1: :uint256 } do
return {
token0: ERC20(s.token0).balanceOf(address(this)),
token1: ERC20(s.token1).balanceOf(address(this))
}
end
```
And called internally with `t0, t1 = reserves()`.
In Solidity for internal calls you must immediately destructure such return values. We cannot enforce this, so we wrap them in an object that can't really do anything but be destructured and can only be destructured once.

Enable multiple return values

---

app/controllers/contracts_controller.rb
spec/contracts_controller_spec.rb

For Javascript.
Maybe in the future we can abstract this into
`app/controllers/concerns/response_formatting.rb`
```ruby
module ResponseFormatting
extend ActiveSupport::Concern
def format_response(result)
if result.is_a?(Integer)
result.to_s
elsif result.is_a?(Hash)
result.as_json.deep_transform_values do |value|
value.is_a?(Integer) ? value.to_s : value
end
else
result
end
end
end
```
```ruby
class ContractsController < ApplicationController
include ResponseFormatting
def static_call
cooked_result = format_response(result)
render json: {
result: cooked_result
}
end
end
```

Static call results should convert integers to strings

---

app/models/abi_proxy.rb
app/models/contracts/erc20_liquidity_pool.rb
app/models/contracts/erc721.rb
app/models/contracts/ether_bridge.rb
app/models/contracts/generative_erc721.rb
app/models/contracts/open_edition_erc721.rb
app/models/contracts/uniswap_v2_factory.rb
app/models/contracts/uniswap_v2_pair.rb
app/models/contracts/uniswap_v2_router.rb
spec/models/contract_implementation_spec.rb
spec/models/inheritance_spec.rb
spec/models/uniswap_v2_pair_spec.rb

Now you must (manually if necessary) return nil if the signature calls for it and if the signature doesn't call for it you cannot return nil.
However you're allowed to return whatever you want from a constructor because they always have return value nil

Stronger function return type enforcement

---

app/models/contract.rb
app/models/contract_call.rb
app/models/contract_errors.rb
spec/models/contract_call_spec.rb

Previously we were silently rolling the change back. But this error means something is wrong with the contract definition.

Raise exception if read-only function tried to update state

---

app/models/ethscription.rb
app/models/ethscription_sync.rb

Previously we were constantly deleting and re-adding the most recent transaction which led to some weird behavior.

Stop always deleting earliest imported ethscription

---

app/controllers/contracts_controller.rb
app/models/contract.rb
app/models/contract_transaction.rb
config/environments/development.rb

Static calls and simulations are completely deterministic based on their inputs and the state of the VM. Therefore the VM shouldn't recompute unless state or inputs change.
This PR achieves this by using key-based memcache cache expiry.

Cache static call and simulation results

---

app/models/contract_test_helper.rb
app/models/contract_transaction.rb
app/models/eth_block.rb
app/models/ethscription.rb
app/models/ethscription_sync.rb
db/migrate/20230928185853_create_eth_blocks.rb
db/structure.sql
spec/models/contract_state_spec.rb

Previously we were going one ethscription at a time. This was very fast but ultimately too difficult to make completely reorg resistant. Now we import blocks atomically and detect reorgs by verifying parent blockhashes.

Import new ethscriptions one block at a time

---

Gemfile
Gemfile.lock
Procfile
app/controllers/status_controller.rb
app/models/contract_test_helper.rb
app/models/contract_transaction.rb
app/models/eth_block.rb
app/models/ethscription.rb
app/models/ethscription_sync.rb
app/models/function_context.rb
config/clock.rb
config/processor_clock.rb
db/migrate/20231001152142_add_contract_actions_processed_at.rb
db/structure.sql
spec/models/contract_state_spec.rb

Also we now skip processing blocks with no ethscriptions (though we do import them to ensure we haven't missed anything).
This speeds things up significantly when ethscriptions are spread out among many blocks. However when ethscriptions are dense the time to process them is the dominant factor and the improvements here are marginal.

Separate ethscription downloading from ethscription processing

---

app/models/contracts/TokenUpgradeRenderer02.rubidity
lib/rubidity/contract_implementation.rb
lib/rubidity/transaction_execution/transaction_context.rb
spec/models/nft_upgrade_spec.rb

Ability to have multiple image URIs on an upgrade level and choose randomly between them.
Ideally we wouldn't need a separate mapping for the array but right now structs don't support arrays OR adding fields on upgrade.
Here's the contract diff:
```diff
diff --git a/app/models/contracts/TokenUpgradeRenderer01.rubidity b/app/models/contracts/TokenUpgradeRenderer01.rubidity
index d7f83b3..8830d8c 100644
--- a/app/models/contracts/TokenUpgradeRenderer01.rubidity
+++ b/app/models/contracts/TokenUpgradeRenderer01.rubidity
@@ -8,7 +8,7 @@ contract :INFTCollection01, abstract: true do
function :owner, :external, :view, returns: :address
end
-contract :TokenUpgradeRenderer01, is: :Upgradeable, upgradeable: true do
+contract :TokenUpgradeRenderer02, is: :Upgradeable, upgradeable: true do
event …
```

Ability to have multiple image URIs on an upgrade level
